'use client';
import type { InvoiceDetails } from '@/lib/invoice-details';
const num=(n:number|null)=>n===null?'Não informado':n.toLocaleString('pt-BR',{maximumFractionDigits:6});
const money=(n:number|null)=>n===null?'Não informado':n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export default function InvoiceDetailsPanel({details,total,onChange}:{details:InvoiceDetails;total:number;onChange:(d:InvoiceDetails)=>void}) {
  const fields: Array<[keyof InvoiceDetails,string]>=[['cliente','Cliente'],['documento','CPF / CNPJ'],['unidade_consumidora','Unidade consumidora'],['endereco','Endereço'],['grupo','Grupo'],['subgrupo','Subgrupo'],['classificacao','Classificação'],['modalidade','Modalidade'],['fornecimento','Fornecimento'],['vencimento','Vencimento'],['leitura_anterior','Leitura anterior'],['leitura_atual','Leitura atual'],['proxima_leitura','Próxima leitura']];
  return <section className="space-y-4 rounded-2xl border bg-white p-6"><h2 className="text-xl font-bold">Conferência dos dados da fatura</h2><p className="text-sm">Confira os campos com o PDF original. Identificação e datas podem ser corrigidas abaixo; campos ausentes permanecem como não identificados.</p>
    <div className="grid gap-3 sm:grid-cols-2">{fields.map(([key,label])=><label className="text-sm" key={key}>{label}<input className="mt-1 w-full rounded border p-2" placeholder="Não identificado" value={typeof details[key]==='string'?details[key] as string:''} onChange={e=>onChange({...details,[key]:e.target.value||null})}/></label>)}</div>
    <p>Perdas de transformação / ramal: {num(details.perdas_percentual)}%</p>
    <h3 className="font-bold">Itens cobrados e créditos identificados</h3>
    <div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr>{['Item','Quantidade','Tarifa com tributos','Tarifa sem tributos','PIS/COFINS','ICMS','Valor'].map(h=><th key={h} className="border-b p-2">{h}</th>)}</tr></thead><tbody>{details.itens.map((item,i)=><tr key={i}>{[item.descricao,num(item.quantidade),num(item.tarifa_com_tributos),num(item.tarifa_sem_tributos),money(item.pis_cofins),money(item.icms),money(item.valor)].map((v,j)=><td key={j} className="border-b p-2">{v}</td>)}</tr>)}</tbody></table></div>
    <p className="rounded bg-slate-50 p-3 text-sm">Soma dos itens: {money(details.soma_itens)}. Total da conta: {money(total)}. {details.soma_itens!==null&&Math.abs(details.soma_itens-total)<0.02?'Valores conciliados.':'Extração incompleta ou divergente: conferir itens no original.'} Tributos são demonstrativos e não devem ser somados novamente.</p>
    <h3 className="font-bold">Tributos demonstrados</h3>{details.tributos.map(t=><p key={t.nome} className="text-sm">{t.nome}: base {money(t.base)} · alíquota {num(t.aliquota)}% · valor {money(t.valor)}</p>)}
    {details.historico_ativo_injetado.length>0&&<details><summary className="font-bold">Histórico de energia ativa e injetada</summary><p className="text-sm">O gráfico da fatura mostra ativo/injetado; não representa reativo excedente.</p><table className="w-full text-sm"><thead><tr><th>Mês</th><th>Ativo (kWh)</th><th>Injetado (kWh)</th></tr></thead><tbody>{details.historico_ativo_injetado.map(h=><tr key={h.mes}><td>{h.mes}</td><td>{num(h.ativo_kwh)}</td><td>{num(h.injetado_kwh)}</td></tr>)}</tbody></table></details>}
    <details><summary className="font-bold">Todo o texto extraído do PDF</summary><p className="text-xs">Para conferir mensagens, avisos e dados que não tenham sido estruturados. PDFs sem camada de texto exigem outro processo de leitura.</p><pre className="max-h-96 overflow-auto whitespace-pre-wrap rounded bg-slate-50 p-3 text-xs">{details.texto_extraido}</pre></details>
  </section>;
}
